### ISSUE TITLE
missing files in source code release

### ISSUE THREAD

**Issue by ghost** [kugelrund/Speed-Outcast#1]
Hey kugelrund,
After I opened the source code (using visual studio 2017), the code explorer references three files in the "speedrun/overbounce_detection" directory, namely OverbouncePrediction.cpp, OverbouncePrediction.hpp, and RingBuffer.hpp. These files are nowhere to be found in the actual .zip or .tar.gz you have posted. Could you please update them so that we can read the code? Thanks ahead of time [:

EDIT: Also, the files in the "speedrun/strafe_helper" directory are missing too, namely StrafeHelper.cpp and StrafeHelper.hpp. If you could, please also include those!

P.S.: what IDE and compiler did you use for the creation of your binary and dll? I don't see it listed anywhere; e.g. is it updated to modern visual studio or should I be using VS2005 like the original game does? cheers

**Comment by kugelrund** [comment]
Those "missing" files are from the repositories https://github.com/kugelrund/overbounce_prediction and https://github.com/kugelrund/strafe_helper respectively. Both repositories are included as so called submodules, which you can read more about [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules). After cloning this repository, change into the newly created directory and use the command `git submodule update --init` to initialize the submodules and thereby retrieve the files. Visual Studio 2017 with it's corresponding compiler is used for the binaries that you can find in the release section.
